### ISSUE TITLE
Bug: 百度贴吧签到不能签到C++吧

### ISSUE THREAD

**Issue by MukjepScarlet** [sakura-flutter/tampermonkey-scripts#635]
我猜是字符串处理有问题 用的是模拟APP签到 Python端https://github.com/MukjepScarlet/Toolkit/blob/main/Python/%E8%B4%B4%E5%90%A7%E8%87%AA%E5%8A%A8%E7%AD%BE%E5%88%B0.py 还没有测试 明天若有问题继续追加

**Comment by MukjepScarlet** [comment]
我在Python上也签到失败

**Comment by MukjepScarlet** [comment]
破案了 傻逼百度 我用安卓端贴吧直接进不去C++吧 直接跳到C吧了

**Comment by MukjepScarlet** [comment]
我已经解决该问题。问题原因是百度默认的接口在传参时是用URL形式提交的，"+"在URL里需要用"%2B"表示。同时汉字也应该用%来表示(虽然直接使用也是可以的)。我的方法是用Python的库函数进行URL字符串编码，JS应该也有相关函数可以调用。

**Comment by sakura-flutter** [comment]
纳尼，还有这种问题
我看看哈

**Comment by sakura-flutter** [comment]
谢谢哈~
