### ISSUE TITLE
您好，链接跳转能否增加熊猫OCR的支持

### ISSUE THREAD

**Issue by lyjhyjyes** [sakura-flutter/tampermonkey-scripts#647]
https://support.qq.com/products/322047/faqs-more
6. 打开：[https://fanyi-api.baidu.com/api/trans/product/desktop?req=developer](https://support.qq.com/products/322047/link-jump?jump=https%3A%2F%2Ffanyi-api.baidu.com%2Fapi%2Ftrans%2Fproduct%2Fdesktop%3Freq%3Ddeveloper)，复制或记下红框内容：
打开第六项，弹出跳转弹窗，麻烦。谢谢

**Comment by sakura-flutter** [comment]
哇噢，非常感谢！
